In [1]:
import numpy as np

In [2]:
my_arr= np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr*2

CPU times: user 5.28 ms, sys: 7.75 ms, total: 13 ms
Wall time: 15.1 ms


In [6]:
%time for _ in range(10): my_list2 = [my_list * 2]

CPU times: user 56.4 ms, sys: 19 ms, total: 75.3 ms
Wall time: 86.6 ms


In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[ 1.56199194,  0.28362545,  0.74652622],
       [ 0.25151334, -0.05293722,  0.30306015]])

In [9]:
data* 10

array([[15.61991943,  2.83625447,  7.4652622 ],
       [ 2.51513342, -0.5293722 ,  3.03060147]])

In [10]:
data+data

array([[ 3.12398389,  0.56725089,  1.49305244],
       [ 0.50302668, -0.10587444,  0.60612029]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int64')

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [30]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [31]:
arr1.dtype

dtype('float64')

In [32]:
arr2.dtype

dtype('int32')

In [33]:
arr = np.array([1,2,3,4,5])

In [34]:
arr.dtype

dtype('int64')

In [36]:
float_arr = arr.astype(np.float64)

In [37]:
float_arr.dtype

dtype('float64')

In [38]:
numeric_strings = np.array(['1.25', '-9.6', '42.5'])

In [39]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.5 ])

In [40]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [41]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [42]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [43]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [44]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [45]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [46]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [47]:
arr = np.arange(10)

In [48]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr[5]

np.int64(5)

In [50]:
arr[5:8]

array([5, 6, 7])

In [51]:
arr[5:8] = 12

In [52]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [53]:
arr = np.empty((8,4))

In [54]:
for i in range(8):
    arr[i] = i

In [55]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [56]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])